export const Op = {
    Jump: 1,
    END: 2,
    I8: 3,
    I32: 4,
    BOOL: 5,
    String: 6,
    JumpIfFalse: 7,
    JumpToBlock: 8,

    //binary expressions
    LessThan: 9,
    LessThanOrEqual: 10,
    GreaterThan: 11,
    GreaterThanOrEqual: 12,
    EqualTo: 13,
    EqualToStrict: 14,
    NotEqualTo: 15,
    NotEqualToStrict: 16,
    Add: 17,
    Sub: 18,
    Divide: 19,
    Multiply: 20,
    Remainder: 21,
    BitAnd: 22,
    BitOr: 23,
    BitXOR: 24,
    BitLeftShift: 25,
    BitRightShift: 26,
    BitZeroFillRightShift: 27,
    RaiseExponent: 28,

    AssignValue: 29,
    AssignValueToGlobal: 30,
    GetVariableValue: 31,
    GetObjectProperty: 32,
    SetObjectProperty: 33,
    GetGlobalVariableValue: 34,
    CreateFunction: 35,
    Call: 36,
    ObjectPropertyCall: 37,
    ReturnValue: 38,
    RegisterString: 39,

    MakeArray: 40,
    MakeObject: 41,
    This: 42,
    GetArguments: 43,
    Debugger: 44,
    PlusPlus: 45,
    New: 46,
};